from __future__ import annotations

MANUAL_CORE_EXAMPLES = {
    "actual": "The actual cost was much higher than we expected.",
    "conduct": "His conduct during the investigation damaged his reputation.",
    "direct": "She gave me direct instructions before the meeting began.",
    "anticipate": "We did not anticipate such a strong response from readers.",
    "steer": "She gently steered the conversation back to the main topic.",
    "reign": "The castle was rebuilt during the reign of Henry VIII.",
    "monarch": "The young monarch addressed the nation from the palace.",
    "embarrass": "I did not mean to embarrass you in front of everyone.",
    "dismay": "To her dismay, the train left a minute early.",
    "detain": "The police were allowed to detain the suspect overnight.",
    "entire": "The entire village came out to welcome the team.",
    "require": "Most universities require two letters of recommendation.",
    "profit": "The company made a modest profit in its first year.",
    "prolong": "The medicine may prolong the patient's life.",
    "boost": "The new policy should boost consumer confidence.",
    "splash": "The passing bus splashed muddy water onto my coat.",
    "condense": "You can condense the report into a single page.",
    "compact": "The apartment was compact but surprisingly comfortable.",
    "squeeze": "She squeezed some lemon juice over the fish.",
    "discourage": "The high cost may discourage students from applying.",
    "encourage": "Good teachers encourage students to ask questions.",
    "confidential": "The interview records will remain confidential.",
    "bald": "He went bald in his early thirties.",
    "petition": "Residents signed a petition against the new road.",
    "tragedy": "The fire was a tragedy for the entire town.",
    "novel": "She is reading a novel set in nineteenth-century Paris.",
    "humiliate": "His rude joke was meant to humiliate her.",
    "humble": "Despite his success, he remained humble and approachable.",
    "chaos": "Traffic chaos followed the sudden closure of the bridge.",
    "create": "The program was created to help first-year students adjust.",
    "concrete": "We need concrete evidence before making such a serious claim.",
    "admit": "She finally admitted that she had made a mistake.",
    "transport": "Public transport is cheaper than driving in the city.",
    "cliff": "We stood at the edge of the cliff and watched the sea.",
    "step": "Please watch your step on the wet stairs.",
    "patent": "The company filed a patent for the new device.",
    "accuse": "They accused him of leaking the report to the press.",
    "single": "Not a single complaint was received that week.",
    "uphold": "The court upheld the earlier decision.",
    "ambiguous": "His answer was so ambiguous that nobody knew what he meant.",
    "dim": "The room was dim after the lamps were switched off.",
    "cement": "They used cement to repair the cracked wall.",
    "caution": "The doctor advised caution after the operation.",
    "punish": "Teachers should guide students, not simply punish them.",
    "exceptional": "She has shown exceptional skill for someone her age.",
    "derive": "Many English words derive from Latin.",
    "thrive": "Small businesses can thrive with the right support.",
    "bond": "A strong bond grew between the coach and the players.",
    "bind": "The treaty will bind both sides to the agreement.",
    "bound": "The two ideas are closely bound together.",
    "abound": "Wildflowers abound in the valley in early summer.",
    "prone": "Children are more prone to colds in winter.",
    "option": "Working from home is not an option for everyone.",
    "trend": "The latest figures show an upward trend in sales.",
    "contend": "Several teams are expected to contend for the title.",
    "screen": "The old cinema still has a huge screen.",
    "conceal": "He tried to conceal his disappointment behind a smile.",
    "intensive": "She spent two weeks in intensive training.",
    "overcome": "She worked hard to overcome her fear of speaking.",
    "swear": "He swore that he had told the truth.",
    "violate": "These actions violate basic human rights.",
    "retail": "The shoes retail for about eighty dollars.",
    "wholesale": "Most goods are sold wholesale before they reach shops.",
    "worthy": "Her work is worthy of greater attention.",
    "restrain": "She could hardly restrain her laughter.",
    "hammer": "He hit the nail with a heavy hammer.",
    "resemble": "The twins resemble each other closely.",
    "clash": "Their views on education often clash.",
    "fake": "The website sold fake designer bags.",
    "confuse": "The two brothers are so alike that people often confuse them.",
    "diffuse": "Morning light spread in a diffuse glow through the curtains.",
    "abnormal": "The doctor noticed an abnormal heartbeat.",
    "infirm": "He grew old and infirm after years of hard labor.",
    "locate": "Rescue teams were unable to locate the missing hikers.",
    "attach": "Please attach your resume to the email.",
    "cling": "Wet clothes clung to her skin.",
    "tractor": "A red tractor was parked beside the barn.",
    "tutor": "A private tutor helped him prepare for the exam.",
    "confine": "The disease is largely confined to rural areas.",
    "supervise": "A nurse will supervise the children during lunch.",
    "visual": "The lecture included several useful visual aids.",
    "appreciate": "I really appreciate your honesty.",
    "entitle": "This ticket entitles you to a free drink.",
    "superficial": "He made only a superficial study of the problem.",
    "esteem": "She is held in high esteem by her colleagues.",
    "switch": "He pressed the switch and the machine started.",
    "prosper": "The town prospered after the railway arrived.",
    "insulate": "Thick curtains help insulate the room in winter.",
    "script": "The actor learned the entire script in a week.",
    "consist": "The committee consists of eight members.",
    "reserve": "We'd like to reserve a table for two.",
    "foresee": "Nobody could foresee the scale of the crisis.",
    "portable": "The speaker is small, light, and portable.",
    "oblige": "The contract does not oblige you to stay.",
    "prosecute": "The state decided to prosecute the driver.",
    "crime": "The city has seen a drop in violent crime.",
    "numerical": "The report includes detailed numerical data.",
    "bore": "The drill can bore through solid rock.",
    "deceive": "Appearances can deceive even careful observers.",
    "idle": "Several workers stood idle by the closed gate.",
    "moderate": "He takes a moderate position on most issues.",
    "demonstrate": "The experiment demonstrates how the device works.",
    "staff": "The hotel staff were polite and efficient.",
    "despair": "After months of failure, he began to despair.",
    "glance": "She gave the letter a quick glance.",
    "originate": "The rumor is believed to have originated online.",
    "harness": "The rescue team used a harness to lower him safely.",
    "semiconductor": "Silicon is the semiconductor most commonly used in chips.",
    "dense": "The fog was so dense that we could barely see the road.",
    "scratch": "I scratched my hand on a rusty nail.",
    "setback": "The injury was a major setback for her training plan.",
    "single": "She was a single mother raising two children.",
    "rebel": "The rebels took control of the radio station.",
    "strain": "The sudden move put a strain on their finances.",
    "inhibit": "Fear can inhibit creativity.",
    "mercy": "The judge showed mercy because it was his first offense.",
    "sympathy": "She wrote a letter of sympathy to the family.",
    "powder": "The box was covered in fine white powder.",
    "nutrition": "Good nutrition is essential for children's growth.",
    "fancy": "She wore a fancy hat to the party.",
    "rage": "He flew into a rage when he saw the damage.",
    "evil": "The novel describes the struggle between good and evil.",
    "harmony": "The building is in perfect harmony with its surroundings.",
    "theory": "In theory, the plan sounds simple.",
    "genuine": "Her surprise looked completely genuine.",
    "crude": "The sketch was crude but effective.",
    "identify": "Can you identify the man in this photograph?",
    "identical": "The twins were dressed in identical coats.",
    "hybrid": "The company plans to release a new hybrid car.",
    "complex": "This is a complex problem with no easy answer.",
    "puzzle": "The last question on the test puzzled me.",
    "complain": "Several neighbors complained about the noise.",
    "affluent": "The area is home to many affluent families.",
    "disgust": "The smell of the drain filled him with disgust.",
    "abandon": "They had to abandon the car in the snow.",
    "uniform": "All students must wear a school uniform.",
    "ensure": "Please ensure that all windows are locked.",
    "structure": "The structure was damaged in the storm.",
    "construction": "Road construction caused heavy delays.",
    "affect": "Lack of sleep can affect your memory.",
    "utility": "The utility company restored power by noon.",
    "flaw": "There is a fatal flaw in your argument.",
    "submerge": "The flood threatened to submerge the bridge.",
    "fade": "The paint has faded in the sun.",
    "economy": "The economy grew more slowly this quarter.",
    "mostly": "The audience was composed mostly of students.",
    "civil": "Despite their disagreement, they remained civil.",
    "metropolis": "Tokyo is one of the world's largest metropolises.",
    "federal": "The case was heard in federal court.",
    "grave": "The doctor spoke in a grave voice.",
    "grant": "The foundation awarded her a research grant.",
    "reciprocal": "The agreement brought reciprocal benefits to both sides.",
    "conscious": "He was still conscious after the accident.",
    "extract": "The article was extracted from her new book.",
    "epidemic": "Doctors are trying to contain the epidemic.",
    "scholar": "He was a respected scholar of Chinese history.",
    "board": "She wrote the answer on the board.",
    "semester": "The spring semester begins in March.",
    "contemplate": "She sat by the river to contemplate her future.",
    "vain": "All our efforts were in vain.",
    "compete": "Athletes from twenty countries will compete here.",
    "refine": "The company hopes to refine the process.",
    "definite": "We still do not have a definite answer.",
    "infinite": "The sky seemed infinite above the desert.",
    "preliminary": "The committee released its preliminary findings.",
    "restrict": "New rules restrict traffic in the old town.",
    "rigorous": "The training program is physically rigorous.",
    "withhold": "The witness chose to withhold that detail.",
    "stable": "Prices have remained stable for months.",
    "comprise": "Women comprise more than half the workforce.",
    "operate": "The clinic operates seven days a week.",
    "elaborate": "He asked her to elaborate on her proposal.",
    "dose": "The doctor adjusted the dose carefully.",
    "positive": "She is positive that she locked the door.",
    "oppose": "Many residents oppose the new airport plan.",
    "envy": "He looked at her success with envy.",
    "visible": "The mountains were barely visible through the mist.",
    "angle": "The photograph was taken from a low angle.",
    "include": "The price includes breakfast.",
    "suspend": "The airline suspended all flights for the night.",
    "proceed": "After a short pause, he proceeded with the lecture.",
    "process": "The visa process can take several weeks.",
    "concede": "He was unwilling to concede defeat.",
    "recession": "Many families struggled during the recession.",
    "latitude": "Teachers need some latitude in the classroom.",
    "aggressive": "The company adopted an aggressive marketing strategy.",
    "minister": "The finance minister spoke to reporters after the meeting.",
    "administer": "The nurse administered the medicine slowly.",
    "devalue": "A currency can lose trust quickly when leaders devalue it.",
    "assume": "We cannot assume that everyone agrees.",
    "accommodate": "The hotel can accommodate up to two hundred guests.",
    "adopt": "Many schools have adopted online teaching tools.",
    "largely": "The success of the project was largely due to her efforts.",
    "heighten": "The speech only heightened public concern.",
    "flexible": "We need a more flexible schedule.",
    "subject": "The lecture covered a difficult subject.",
    "object": "She did not object to the suggestion.",
    "objective": "Our main objective is to improve safety.",
    "majority": "A clear majority supported the proposal.",
    "major": "He played a major role in the campaign.",
    "beat": "Her heart beat faster as the lights went out.",
    "monotonous": "The work was dull and monotonous.",
    "variation": "There is some variation in color from one flower to another.",
    "reverse": "He reversed the car into the driveway.",
    "controversy": "The decision sparked fierce controversy.",
    "spy": "The government arrested a suspected spy.",
    "suspect": "Police suspect that the fire was started deliberately.",
    "respect": "Children should show respect for others.",
    "spectator": "Thousands of spectators filled the stadium.",
    "communicate": "We communicate by email most of the time.",
    "mutual": "The two countries signed a mutual defense pact.",
    "integrate": "The school works hard to integrate new students.",
    "segregate": "The policy effectively segregated poor families from the center.",
    "random": "The survey selected fifty people at random.",
    "graduate": "She will graduate from college next year.",
    "senior": "A senior manager approved the plan.",
    "boycott": "Consumers threatened to boycott the brand.",
    "interpret": "Different readers may interpret the poem differently.",
    "interview": "I have a job interview on Friday morning.",
    "worm": "A bird pulled a worm from the wet soil.",
    "proclaim": "The king proclaimed a day of celebration.",
    "reclaim": "The city hopes to reclaim the old industrial site.",
    "exclaim": "She exclaimed in surprise when she saw the cake.",
    "announce": "They announced the results at noon.",
    "advertise": "Small companies cannot afford to advertise on television.",
    "veteran": "A veteran reporter covered the trial.",
    "sane": "No sane person would take that risk lightly.",
    "renaissance": "The city is enjoying a cultural renaissance.",
    "veto": "The president threatened to veto the bill.",
    "item": "I bought a few items for dinner.",
    "draft": "She wrote a first draft of the essay last night.",
    "constitution": "The constitution protects freedom of speech.",
    "substitute": "Yogurt can be used as a substitute for cream.",
    "displace": "The flood displaced hundreds of residents.",
    "obedient": "The dog is gentle and obedient.",
    "solid": "The table is made of solid oak.",
    "clarity": "Her explanation brought clarity to the debate.",
    "appeal": "The charity launched an appeal for donations.",
    "verdict": "The jury returned a guilty verdict.",
    "decent": "He earns a decent salary.",
    "mild": "We had a mild winter this year.",
    "giant": "A giant screen stood behind the stage.",
    "tremendous": "They made tremendous progress in a short time.",
    "enormous": "The bridge required an enormous amount of steel.",
    "superfluous": "Most of the introduction felt superfluous.",
    "multiply": "Bacteria multiply rapidly in warm conditions.",
    "host": "She will host the conference this year.",
    "persuade": "Nobody could persuade him to change his mind.",
    "lobby": "Several companies lobbied against the law.",
    "agent": "A travel agent helped us plan the trip.",
    "trick": "It was only a cheap trick to gain attention.",
    "retreat": "The army was forced to retreat.",
    "rough": "The road became rough after the storm.",
    "absolute": "We need absolute trust in this work.",
    "negative": "She received some negative feedback.",
    "ignorant": "He was ignorant of the local customs.",
    "annoy": "Loud chewing noises annoy me.",
    "cheat": "He was caught trying to cheat in the exam.",
    "fraud": "The company was accused of tax fraud.",
    "stride": "She strode across the room without hesitation.",
    "crawl": "The baby began to crawl across the carpet.",
    "tag": "Please tag your suitcase before boarding.",
    "faint": "She heard a faint sound from upstairs.",
    "dizzy": "The spinning ride made me dizzy.",
    "grace": "She moved across the stage with grace.",
    "polish": "He polished his shoes before the interview.",
    "twinkle": "Her eyes twinkled with amusement.",
    "compensate": "The company agreed to compensate the workers.",
    "incorporate": "The design incorporates several local motifs.",
    "even": "The road ahead was flat and even.",
    "equivalent": "Eight kilometers is roughly equivalent to five miles.",
    "delay": "Bad weather caused a long delay.",
    "infer": "From her tone, I inferred that she was upset.",
    "reference": "The report makes reference to earlier studies.",
    "prefer": "I prefer tea to coffee.",
    "modest": "He lives in a modest apartment near the station.",
    "indicate": "Dark clouds indicate that rain is coming.",
    "embrace": "She was ready to embrace change.",
    "implicit": "The agreement carried an implicit promise of support.",
    "explicit": "The instructions were clear and explicit.",
    "invest": "They plan to invest in renewable energy.",
    "survey": "We carried out a survey of local residents.",
    "convey": "His face conveyed deep disappointment.",
    "foam": "Sea foam covered the rocks.",
    "defend": "Lawyers were hired to defend the company.",
    "scan": "She scanned the page for his name.",
    "initiate": "The company will initiate a formal review.",
    "primary": "Our primary concern is patient safety.",
    "prime": "The minister met the prime suspect yesterday.",
    "origin": "The legend has its origin in medieval Europe.",
    "resource": "Fresh water is a limited resource in this region.",
    "schedule": "The train is running behind schedule.",
    "incur": "You may incur extra charges if you return the car late.",
    "bargain": "At that price, the coat was a real bargain.",
    "frontier": "Researchers are working at the frontier of medical science.",
    "arouse": "The article aroused public anger.",
    "recreation": "The park was designed for rest and recreation.",
    "retire": "He plans to retire at sixty-five.",
    "allowance": "My parents gave me a small weekly allowance.",
    "profound": "The war had a profound effect on his life.",
    "impact": "The decision will have a lasting impact on local schools.",
    "hollow": "The sound echoed through the hollow tree.",
    "shallow": "The water is too shallow for boats here.",
    "dump": "Someone had dumped old tires by the river.",
    "massive": "A massive storm moved across the coast overnight.",
    "creature": "The creature vanished into the forest.",
    "present": "All staff members were present at the meeting.",
    "dismiss": "The judge dismissed the case for lack of evidence.",
    "missile": "The missile was intercepted before it reached the city.",
    "emit": "The machine emits a loud warning sound.",
    "permit": "You cannot enter the site without a permit.",
    "commit": "He refused to commit himself to a date.",
    "opaque": "The glass was opaque and let in little light.",
    "striking": "She bears a striking resemblance to her mother.",
    "evidence": "There is clear evidence that the river is polluted.",
    "approve": "The board approved the budget without debate.",
    "frank": "She gave me a frank answer.",
    "complete": "The building is almost complete.",
    "ignite": "Dry leaves can ignite very easily in summer.",
    "quarrel": "The brothers had a bitter quarrel over money.",
    "engage": "The book is written to engage young readers.",
    "divorce": "They decided to divorce after ten years of marriage.",
    "fierce": "A fierce wind blew across the fields.",
    "prudent": "It would be prudent to save some money for emergencies.",
    "rent": "They rent a small apartment near the station.",
    "fabulous": "She looked fabulous in the blue jacket.",
    "extraordinary": "She showed extraordinary courage in the crisis.",
    "eminent": "The lecture was delivered by an eminent historian.",
    "pull": "He pulled the door open with both hands.",
    "advisable": "It is advisable to back up your files regularly.",
    "agony": "He waited in agony for the test results.",
    "distort": "The mirror distorted her reflection.",
    "statement": "The minister issued a brief statement to reporters.",
    "delicate": "The negotiation reached a delicate stage.",
    "decay": "The wooden steps have begun to decay.",
    "turbulent": "The country went through a turbulent period.",
    "auction": "The painting will be sold at auction next week.",
    "protest": "Thousands marched in protest against the law.",
    "detest": "I detest waking up before dawn.",
    "decline": "Sales began to decline in late autumn.",
    "intention": "It was never my intention to offend anyone.",
    "enclose": "I enclose a copy of the receipt with this letter.",
    "sense": "I had the sense that something was wrong.",
    "senseless": "The attack was a senseless act of violence.",
    "curious": "The child was curious about everything around him.",
    "secure": "The museum has taken steps to secure the painting.",
    "peculiar": "There was a peculiar smell in the hallway.",
    "weird": "I had a weird dream last night.",
    "exploit": "Some companies exploit cheap labor abroad.",
    "explode": "A gas pipe exploded under the street.",
    "virus": "Doctors are monitoring the spread of the virus.",
    "bacteria": "Some bacteria are useful in making yogurt.",
    "physical": "The job demands great physical strength.",
    "crucial": "It is crucial to keep accurate records.",
    "responsible": "Who is responsible for the missing files?",
    "ultimate": "Trust is the ultimate test of friendship.",
    "temper": "He struggled to control his temper.",
    "spray": "She used a fine spray of water on the plants.",
    "pray": "They gathered to pray for the injured workers.",
    "scope": "The study is small in scope but valuable.",
    "vibrate": "The phone began to vibrate in my pocket.",
    "entail": "The job will entail frequent travel.",
    "hazard": "Loose wires can be a serious hazard.",
    "strap": "Fasten the bag with the leather strap.",
    "property": "The family sold the property last year.",
    "ownership": "Home ownership remains out of reach for many people.",
    "estate": "The family estate was divided among the children.",
    "wealth": "She used her wealth to support local charities.",
    "settle": "It took her months to settle into the new city.",
    "cope": "He found it hard to cope with the pressure.",
    "dissolve": "Sugar dissolves quickly in hot water.",
    "calm": "He tried to remain calm during the interview.",
    "concentrate": "Please concentrate on what the speaker is saying.",
    "addict": "He became addicted to online games as a teenager.",
    "predict": "Experts predict further growth next year.",
    "extinct": "Several species in the region are now extinct.",
    "distinguish": "It is hard to distinguish the twins from a distance.",
    "distinct": "The two concepts are clearly distinct.",
    "sting": "The bee sting left a red mark on her arm.",
    "acute": "She felt acute pain in her shoulder.",
    "terminal": "We waited at the airport terminal for hours.",
    "discover": "Scientists discovered a new species in the rainforest.",
    "rise": "There has been a sharp rise in food prices.",
    "prize": "She won first prize in the writing competition.",
    "compliment": "She took his compliment with a quiet smile.",
    "pension": "He lives on a small pension.",
    "foundation": "Trust is the foundation of any lasting friendship.",
    "toast": "He made some toast while the coffee was brewing.",
    "chunk": "A large chunk of the budget went to housing.",
    "omit": "Please do not omit any relevant details.",
    "transfer": "His transfer to Shanghai took effect in July.",
    "formidable": "She faced a formidable opponent in the final.",
    "victory": "The team celebrated a narrow victory.",
    "blame": "She accepted the blame for the mistake.",
    "skeptical": "Many scientists remain skeptical about the claim.",
    "scale": "We had not realized the scale of the problem.",
    "terror": "The explosion filled the street with terror.",
    "panic": "Panic spread quickly through the crowd.",
    "issue": "Climate change remains a pressing issue.",
    "tissue": "She handed me a tissue when I started to cough.",
    "fabric": "The dress is made from a soft cotton fabric.",
    "criterion": "Cost is not the only criterion for success.",
    "holy": "The temple is regarded as a holy place.",
    "statue": "A bronze statue stood in the center of the square.",
    "principle": "The basic principle is easy to understand.",
    "extend": "The bridge extends across the entire river.",
    "extent": "We did not realize the full extent of the damage.",
    "blur": "Tears blurred the words on the page.",
    "religion": "Religion still plays an important role in his life.",
    "sample": "The nurse took a blood sample.",
    "physician": "You should consult a physician if the pain continues.",
    "digital": "The school is investing in digital learning tools.",
    "sow": "Farmers sow rice in the spring.",
    "irrigate": "These canals irrigate the surrounding farmland.",
    "overthrow": "The rebels attempted to overthrow the government.",
    "fortnight": "I will be away for a fortnight.",
    "sweep": "She used a broom to sweep the floor.",
    "merchant": "The silk merchant had traveled across three provinces.",
    "dwell": "He refused to dwell on past failures.",
    "picnic": "We had a picnic by the lake.",
    "surgeon": "The surgeon spoke to the family after the operation.",
    "therapy": "She is receiving therapy for her injured knee.",
    "grip": "He tightened his grip on the railing.",
    "electron": "An electron carries a negative charge.",
    "nuclear": "The country is expanding its nuclear program.",
    "dig": "They began to dig a trench behind the house.",
    "authority": "She spoke with quiet authority.",
    "mortgage": "They are struggling to pay the mortgage.",
    "formation": "Dark clouds gathered in a strange formation.",
    "pledge": "He made a public pledge to reduce waste.",
    "facility": "The new sports facility opened last month.",
    "surge": "There was a sudden surge in demand.",
    "target": "The company failed to meet its sales target.",
    "aim": "The main aim of the course is to improve writing.",
    "quantity": "Quality matters more than quantity.",
    "utmost": "Please treat this matter with the utmost care.",
    "local": "The local market opens at dawn.",
    "curriculum": "The school has revised its science curriculum.",
    "vision": "Her vision of the future was bold and clear.",
    "propel": "Curiosity propelled him into research.",
    "precedent": "The ruling may set an important precedent.",
    "proficient": "She is proficient in both French and German.",
    "artificial": "The lake looked beautiful, though it was entirely artificial.",
    "acrobat": "The acrobat landed lightly on the mat.",
    "monster": "The child was frightened by the movie monster.",
    "dispute": "The wage dispute lasted for months.",
    "joint": "The two companies issued a joint statement.",
    "range": "The shop sells a wide range of books.",
    "undergraduate": "An undergraduate asked a question at the lecture.",
    "postgraduate": "He is now a postgraduate student at Oxford.",
    "kidnap": "The gang planned to kidnap the businessman.",
    "version": "This is the final version of the report.",
    "exsert": "The flower has long, exsert stamens.",
    "overpass": "We waited under the overpass until the rain stopped.",
    "proportion": "A large proportion of the class passed.",
    "provision": "The agreement includes a provision for paid leave.",
    "judgement": "In my judgement, we should wait a little longer.",
    "awe": "The children stared in awe at the night sky.",
    "plausible": "His explanation sounded plausible at first.",
    "agency": "The travel agency booked our flights and hotel.",
    "treaty": "The two countries signed a peace treaty.",
    "passion": "She spoke about music with real passion.",
    "compassion": "The nurse treated every patient with compassion.",
    "conceive": "It is hard to conceive a world without the internet.",
    "flee": "Many villagers had to flee the area at night.",
    "adolescent": "The book explores adolescent anxiety.",
    "stun": "The blow was strong enough to stun him.",
    "elegant": "She wore an elegant black dress.",
    "craft": "It took years to master the craft of editing.",
    "scar": "A thin scar ran across his chin.",
    "analogy": "The teacher used a simple analogy to explain the idea.",
    "symphony": "We listened to a symphony by Beethoven.",
    "channel": "The debate was broadcast on every major channel.",
    "ban": "The city plans to ban smoking in parks.",
    "organ": "The heart is a vital organ.",
    "silence": "An awkward silence followed his question.",
    "scandal": "The scandal forced two officials to resign.",
    "skim": "She skimmed the article before class.",
    "region": "Tea is grown throughout this region.",
}
